Remove uploading repo security scan
Uploading the repo scans caused an error
```
  Processing sarif files: ["trivy-results-repo.sarif"]
  Error: Invalid SARIF. JSON syntax error: Unexpected token 'R', "
  Report Sum"... is not valid JSON
```